Auc 48 입찰하기 비지니스 로직 구현
AuctionProject2022/backend pull request #8
Opened 2022-07-30 00:43 UTC by god-joo

## 💁‍♂️ PR 내용
입찰하기 비지니스 로직 구현

## 🙏 작업
- 입찰하기 구현
- 유효성 체크 

## 🙈 PR 참고 사항
validator 적용은 티켓 새로 만들어서 적용하겠습니다.

2022-08-04 11:09 UTC, gh777kkk reviewed
productId 를 BidPostRequest 로 받지 않고 URL 로 받는 이유가 있을까요 ???

2022-08-05 23:17 UTC, gumicode requested changes

2022-08-05 23:17 UTC, gumicode commented on src/main/java/kr/toyauction/domain/product/controller/ProductController.java
> +	}
입찰하기 비지니스 로직 구현인데, 상품조회 코드가 왜 올라가있죠 ?

2022-08-05 23:17 UTC, gumicode commented on src/main/java/kr/toyauction/domain/product/dto/BidPostResponse.java
> +    private Long id;
id 가 아니라 bidId 를 응답해야 하는거 아닌가요 ?

2022-08-05 23:17 UTC, gumicode commented on src/main/java/kr/toyauction/domain/product/entity/Bid.java
> +    private Long productId;
product 와 밀접하게 연관되어 있는 엔티티 이기 때문에 `@ManyToOne` 으로 설정하는게 좋아 보입니다.

2022-08-05 23:17 UTC, gumicode commented on src/main/java/kr/toyauction/domain/product/dto/BidPostRequest.java
> +    private Integer bidPrice;
`@Min(0)` validation 추가 필요해 보이구요. 가능하다면 `@Max` 값 까지 정의 됬으면 좋겠습니다.

2022-08-05 23:17 UTC, gumicode commented on src/main/java/kr/toyauction/domain/product/service/BidService.java
> +
service 에서 service 를 호출하시면 안됩니다. productRepository 에서 호출해주세요.

2022-08-06 03:56 UTC, god-joo commented
> productId 를 BidPostRequest 로 받지 않고 URL 로 받는 이유가 있을까요 ???

지난번 본수님이 피드백줘서 변경하였는데요~ 
resource가 좀 더 명확하게 구분이 되는 것 같아서 pathVariable을 사용하였습니다.

2022-08-07 00:31 UTC, god-joo commented on src/main/java/kr/toyauction/domain/product/controller/ProductController.java
> +	}
상품목록조회 mock만들고 브랜치 이동하면서 같이 들어간것 같네요^^;
이 부분은 지우겠습니다.

2022-08-07 01:26 UTC, god-joo commented on src/main/java/kr/toyauction/domain/product/dto/BidPostResponse.java
> +    private Long id;
네 맞아요. 수정하겠습니다.

2022-08-10 06:46 UTC, gumicode approved these changes

2022-08-13 00:21 UTC, merged